### ISSUE TITLE
Dark background at several places

### ISSUE THREAD

**Issue by Tekki** [Donearm/Laederon#1]
There are some places where the background remains black and the text is difficult to read or looks strange:

![laederon-background](https://user-images.githubusercontent.com/466122/48554018-8b764300-e8dd-11e8-8d2f-caf3fda1302a.png)

- line numbers, inactive line
- linter marks, inactive line
- netrw and nerdtree, active line
- matching brackets
- and more

PR is on the way.

**Comment by Donearm** [comment]
I don't use Nertdtree not gutter (anymore) so I didn't notice. Thanks for catching it.

Speaking of the specific changes in the PR: all are fine or I'm neutral, thus not a blocker ( :smile: ). I'm gonna merge then
